name: Build JNavTrack

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Qt 6.5.8
        uses: jurplel/install-qt-action@v3
        with:
          version: 6.5.8
          target: desktop
          arch: gcc_64            # для Linux
          cache: true

      - name: Configure CMake
        run: cmake -B build -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=Release

      - name: Build
        run: cmake --build build --config Release

  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Qt 6.5.8
        uses: jurplel/install-qt-action@v3
        with:
          version: 6.5.8
          arch: win64_msvc2019_64
          cache: true

      - name: Configure CMake
        run: cmake -B build -G "NMake Makefiles" -DCMAKE_BUILD_TYPE=Release -DCMAKE_PREFIX_PATH="%Qt6_DIR%"

      - name: Build
        run: cmake --build build --config Release
